<?php
echo $this->getLayout()->createBlock('Magebird\Popup\Block\Widget\Newsletter')->setTemplate('Magebird_Popup::widget/newsletter/global.phtml')->toHtml();
echo $this->getScript(12);
$randomId = $this->getWidgetId();
$color = $this->getButtonColor();
$color1 = $this->brightness($color,10);
$color2 = $this->brightness($color1,-60); 
?>
<style> 
#<?php echo $randomId?>.newsletterPopup form {              
    width: <?php echo $this->getData('width')?><?php echo $this->getData('width_unit')==2 ? "%" : "px";?>;
}

#<?php echo $randomId?>.newsletterPopup form input{
  width: <?php echo $this->getData('width')?>px;
  <?php if($this->getData('width_unit')==2):?>
  width:100%;   
  -moz-box-sizing:    border-box;
  -webkit-box-sizing: border-box;
  box-sizing:        border-box;  
  <?php endif;?>  
}

#<?php echo $randomId?>.newsletterPopup button {   
    color:<?php echo $this->getButtonTextColor()?>; 
    background-color: <?php echo $color; ?>; 
} 
#<?php echo $randomId?>.newsletterPopup form  button:hover{  
    /*background: #c42f2f;*/
  	-ms-filter:"progid:DXImageTransform.Microsoft.Alpha(Opacity=100)";
  	filter: alpha(opacity=100);
  	-moz-opacity:1;
  	-khtml-opacity: 1;
  	opacity: 1;  
}

</style> 
<div class="newsletterPopup tp12" id="<?php echo $randomId?>"> 
  <div class="error" style="display:none;"></div>
  <form method="post" id="popup-newsletter-form" data-widgetId="<?php echo $this->getWidgetId()?>" onsubmit="return false"> 
        <input type="text" placeholder="<?php echo __('Email address')?>" name="email" title="<?php echo __('Enter Your Email')?>" />          
        <button class="shadding shadding1 async_false" type="submit" title="<?php echo __('Subscribe')?>">
        <?php echo $this->getData('button_text') ? $this->getData('button_text') : __('Subscribe') ?>
        </button>
        <button class="shadding shadding1 async_false" type="submit" title="<?php echo $this->__('Subscribe') ?>">
            <?php echo $this->getData('button_text') ? $this->getData('button_text') : $this->__('Subscribe') ?>
        </button>      
  </form>
</div> 