<?php echo $this->getLayout()->createBlock('Magebird\Popup\Block\Widget\Newsletter')->setTemplate('Magebird_Popup::widget/newsletter/global.phtml')->toHtml(); ?>
<?php echo $this->getScript(1)?>
<?php $randomId = $this->getWidgetId(); ?>
<style>
#<?php echo $randomId?>.newsletterPopup form {              
    width: <?php echo $this->getData('width')?><?php echo $this->getData('width_unit')==2 ? "%" : "px";?>;
}

#<?php echo $randomId?>.newsletterPopup form input{
  width: <?php echo $this->getData('width')-20?>px;
  <?php if($this->getData('width_unit')==2):?>
  width:100%;   
  -moz-box-sizing:    border-box;
  -webkit-box-sizing: border-box;
  box-sizing:        border-box;  
  <?php endif;?>
}

#<?php echo $randomId?>.newsletterPopup button {
    background-color: <?php echo $this->getButtonColor(); ?>;  
    width: <?php echo $this->getData('width')-8?>px;    
    color:<?php echo $this->getButtonTextColor()?>;
    <?php if($this->getData('width_unit')==2):?>
    width:100%;   
    -moz-box-sizing:    border-box;
    -webkit-box-sizing: border-box;
    box-sizing:        border-box;  
    <?php endif;?>    
}  
.newsletterPopup .radio{
  width:auto !important;
  display:inline !important;
  margin:0 !important;
}
#newsletterGender{
  margin-bottom:10px;
  padding:7px 0;
  background-color:#dad9d9;
}

#newsletterGender span{
  margin-left:5px;
  margin-right:10px;
  vertical-align:middle;
}

</style>
<div class="newsletterPopup tp1" id="<?php echo $randomId?>"> 
  <div class="error" style="display:none;"></div>
  <form method="post" id="popup-newsletter-form" data-widgetId="<?php echo $this->getWidgetId()?>" onsubmit="return false"> 
      <input type="hidden" name="custom_field_name" value="%GENDER%" />
      <input type="text" placeholder="<?php echo __('First Name')?>" name="first_name" title="<?php echo __('Enter First Name')?>" />
      <input type="text" placeholder="<?php echo __('Last Name')?>" name="last_name" title="<?php echo __('Enter Last Name')?>" />
      <input type="text" placeholder="<?php echo __('Email address')?>" name="email" title="<?php echo __('Enter Your Email')?>" />
      <div id="newsletterGender"> 
      <span>Gender:</span>
      <input type="radio" class="radio" name="custom_field_value" value="male"><span>Male</span> 
      <input type="radio" class="radio" name="custom_field_value" value="female"><span>Female</span>
      </div>          
      <button class="async_false" type="submit" title="<?php echo __('Subscribe')?>">
      <?php echo $this->getData('button_text') ? $this->getData('button_text') : __('Subscribe') ?>
      </button>
  </form>
</div> 