<?php 
echo $this->getLayout()->createBlock('Magebird\Popup\Block\Widget\Buttons')->setTemplate('Magebird_Popup::widget/buttons/global.phtml')->toHtml();
$color = $this->getColor();
$color2 = $this->brightness($color,-44);
?>
<style>
#<?php echo $this->getWidgetId()?>.popupButton{
  border-radius: 8px;
	background-color: <?php echo $color;?>;
	border-bottom: 5px solid <?php echo $color2;?>;
	text-shadow: 0px -1px <?php echo $color2;?>;
  color:<?php echo $this->getButtonTextColor()?>
}  
#<?php echo $this->getWidgetId()?>.popupButton:active{
	transform: translate(0px,5px);
  -webkit-transform: translate(0px,5px);
	border-bottom: 1px solid;
}
</style>      
<?php if($this->getData('on_click')==2 || $this->getData('on_click')==3):?>
  <a href="<?php echo $this->getData('button_href')?>" <?php if($this->getData('link_target')==2) echo 'target="_blank"'?> id="<?php echo $this->getWidgetId()?>" class="popupButton size<?php echo $this->buttonSize(); if($this->getData('on_click')==3) echo ' dialogCloseCustom'?>"><?php echo __($this->getData('button_text'))?></a>
<?php else:?>
  <a href="#" id="<?php echo $this->getData('widget_id')?>" class="popupButton size<?php echo $this->buttonSize()?>"><?php echo __($this->getData('button_text'))?></a>   
  <?php echo $this->getJsHtml()?>
<?php endif;?>