<?php 
echo $this->getLayout()->createBlock('Magebird\Popup\Block\Widget\Buttons')->setTemplate('Magebird_Popup::widget/buttons/global.phtml')->toHtml();
$color = $this->getColor();
$color1 = $this->brightness($color,14);
$color2 = $this->brightness($color,-64);
$color3 = $this->brightness($color,25); 
?>
<style>
#<?php echo $this->getWidgetId()?>.popupButton{
  background-color: <?php echo $color1?>; 
	-moz-border-radius: 1000px;
	-webkit-border-radius: 1000px;
	border-radius: 1000px;        
  color:<?php echo $this->getButtonTextColor()?>
}  
</style>
<?php if($this->getData('on_click')==2 || $this->getData('on_click')==3):?>
  <a href="<?php echo $this->getData('button_href')?>" <?php if($this->getData('link_target')==2) echo 'target="_blank"'?> id="<?php echo $this->getWidgetId()?>" class="popupButton size<?php echo $this->buttonSize(); if($this->getData('on_click')==3) echo ' dialogCloseCustom'?>"><?php echo __($this->getData('button_text'))?></a>
<?php else:?>
  <a href="#" id="<?php echo $this->getData('widget_id')?>" class="popupButton size<?php echo $this->buttonSize()?>"><?php echo __($this->getData('button_text'))?></a>   
  <?php echo $this->getJsHtml()?>
<?php endif;?>