<?php 
echo $this->getLayout()->createBlock('Magebird\Popup\Block\Widget\Buttons')->setTemplate('Magebird_Popup::widget/buttons/global.phtml')->toHtml();
$color = $this->getColor(); 
$color2 = $this->brightness($color,-30);
$color3 = $this->brightness($color,-50);
$color4 = $this->brightness($color,-75);
?>
<style>
#<?php echo $this->getWidgetId()?>.popupButton{
    border: 1px solid;
    border-radius: 4px;
    box-shadow: inset 0 1px 0 0 rgba(255, 255, 255, 0.19); 
    border-color: <?php echo $color2;?> <?php echo $color2;?> <?php echo $color4?> <?php echo $color3?>;
    background-color: <?php echo $color?>; 
		background-image: -webkit-linear-gradient(top, <?php echo $color?> 0%, <?php echo $color2?> 100%);
		background-image: -moz-linear-gradient(top, <?php echo $color?> 0%, <?php echo $color2?> 100%);
		background-image: -ms-linear-gradient(top, <?php echo $color?> 0%, <?php echo $color2?> 100%);
		background-image: -o-linear-gradient(top, <?php echo $color?> 0%, <?php echo $color2?> 100%);
		background-image: linear-gradient(top, <?php echo $color?> 0%, <?php echo $color2?> 100%);
    color:<?php echo $this->getButtonTextColor()?>
}  
</style>
<?php if($this->getData('on_click')==2 || $this->getData('on_click')==3):?>
  <a href="<?php echo $this->getData('button_href')?>" <?php if($this->getData('link_target')==2) echo 'target="_blank"'?> id="<?php echo $this->getWidgetId()?>" class="popupButton size<?php echo $this->buttonSize(); if($this->getData('on_click')==3) echo ' dialogCloseCustom'?>"><?php echo __($this->getData('button_text'))?></a>
<?php else:?>
  <a href="#" id="<?php echo $this->getData('widget_id')?>" class="popupButton size<?php echo $this->buttonSize()?>"><?php echo __($this->getData('button_text'))?></a>   
  <?php echo $this->getJsHtml()?>
<?php endif;?>