<script type="text/javascript">     
  if (typeof popupButton === "undefined"){   
    jQuery('head').append('<link rel="stylesheet" href="<?php echo $block->getViewFileUrl('Magebird_Popup::css/widget/buttons.css') ?>" type="text/css" />');
    var popupButton = {};
    popupButton.ajaxUrl = '<?php echo $this->getAjaxUrl() ?>&rand='+Math.floor((Math.random() * 100000000) + 1)
    popupButton.workingText = '<?php echo __('Working')?>...';    
    var buttonScriptUrl = mb_popup.correctHttps("<?php echo $block->getViewFileUrl('Magebird_Popup::js/button.js') ?>");                                                            
    jQuery.getScript(buttonScriptUrl); 
  }
</script>               