<?php
$color = "#51B500";
?>
<style>

#registerInput li{
  padding:20px 30px;
  background-color:#FFFFFF;
  border:1px solid silver;
  margin-bottom:10px;
  cursor:pointer; 
  width:290px;
}

#registerInput li:hover{
  box-shadow:1px 1px 2px 1px rgba(0,0,0,.1);
}

</style>
<p><?php echo __("Click to the registration form to select template. You can change width and color later.")?></p>
<ul id="registerInput">
<?php for($n=1; $n<4; $n++):?>                                                                                   
  <li onclick='window.submitValue(this,"<?php echo $n;?>");'><img src="<?php echo $this->getViewFileUrl('Magebird_Popup::images/register/'.$n.'.png') ?>" /></li>
<?php endfor;?>
</ul>
<script>
window.submitValue = function ($this,elId){    
    jQuery("input[name='parameters[template]']").val("widget/register/"+elId+".phtml");
    jQuery("input[name='parameters[template]']").parent().parent().parent().prev().find('.widget-option-label').text('Template '+elId)
    jQuery($this).parents('.modal-inner-wrap').find(".action-close").click();
};
</script>