<style>

#timerInput li{
  padding:30px;
  background-color:#f8f8f8;
  border:1px solid silver;
  margin-bottom:10px;
  cursor:pointer; 
}

#timerInput li:hover{
  box-shadow:1px 1px 2px 1px rgba(0,0,0,.1);
}

.calendar{
  z-index:99999;         
}

</style>
<p><?php echo __("Click to the input to select style. You can change size later.")?></p>
<ul id="timerInput">
<?php for($n=1; $n<5; $n++):?>
  <li onclick='window.submitValue(this,"<?php echo $n;?>");'><img src="<?php echo $this->getViewFileUrl('Magebird_Popup::images/timer/'.$n.'.png') ?>" /></li>
<?php endfor;?>
</ul>
<script>
window.submitValue = function ($this,elId){
    jQuery("input[name='parameters[style]']").val(elId);
    jQuery("input[name='parameters[style]']").parent().parent().parent().prev().find('.widget-option-label').text('Template '+elId)
    jQuery($this).parents('.modal-inner-wrap').find(".action-close").click();
};
</script>

        