<style>
.magebirdNotification{
  border:1px solid #3e8acb;
  position:relative;
  padding:10px;
  margin:10px 0;
}

.magebirdNotification.isCriticalNoti{
  border-color:red;
}

.dismissNotification{
  position: absolute;
  right: 0px;
  bottom: 0;
  padding: 0;
  font-size: 10px;
  line-height: 1;
  margin: 5px;
  text-decoration: underline;
  font-weight: bold;
  cursor: pointer;
}
</style>
<?php
$notifications = $this->getNotifications();
foreach($notifications as $noti):
?>
<div data-id="<?php echo $noti['id'];?>" class="magebirdNotification<?php if($noti['is_critical']) echo ' isCriticalNoti'?>">
  <?php echo $noti['notification'];?>
  <p class="dismissNotification" data-id="<?php echo $noti['id'];?>">Dismiss x</p>
</div>
<?php endforeach;?>
<script>
function defer() {
    if (window.jQuery) {
        jQuery(".magebirdNotification").each(function(){
            id = jQuery(this).attr('data-id');
            if(jQuery(".magebirdNotification[data-id='"+id+"']").length>1){
              jQuery(".magebirdNotification[data-id='"+id+"']").not(':first').remove();  
            }  
        });
        
        jQuery(".dismissNotification").click(function(){
            var $this = jQuery(this);
            $this.text('Dismissing...');
            var id = jQuery(this).attr('data-id');
            jQuery.ajax({    
              type: "POST",
              url: "<?php echo $block->getUrl('magebird_popup/index/dismissNotification', ['_current' => true, '_use_rewrite' => true, '_query'=>'isAjax=true'])?>",
              data:'id='+id+'&form_key='+window.FORM_KEY,
              success: function(response){      
                if(response.success=='false'){
                  alert(response.error)
                }else{
                  $this.parent().fadeOut();                 
                }          
              }
            });
          
        });
    } else {
        setTimeout(function() { defer() }, 50);
    }
}
defer()
</script>