<?php echo $this->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magebird_Popup::widget/register/global.phtml')->toHtml(); ?>
<?php $randomId = $this->getWidgetId();?>
<script type="text/javascript">  
rgSuccessMsg['<?php echo $this->getWidgetId()?>'] = decodeURIComponent(('<?php echo urlencode($this->getData('success_msg')) ?>').replace(/\+/g, '%20'));
rgSuccessAction['<?php echo $this->getWidgetId()?>'] = '<?php echo $this->getData('on_success');?>';
rgSuccessUrl['<?php echo $this->getWidgetId()?>'] = '<?php echo $this->getData('success_url');?>';
rgActionDelay['<?php echo $this->getWidgetId()?>'] = '<?php echo $this->getDelay()*1000; ?>'; 
jQuery('head').append('<link rel="stylesheet" href="<?php echo $block->getViewFileUrl('Magebird_Popup::css/widget/register/global.css') ?>" type="text/css" />');
jQuery('head').append('<link rel="stylesheet" href="<?php echo $block->getViewFileUrl('Magebird_Popup::css/widget/register/2.css') ?>" type="text/css" />');
var workingText = '<?php echo __('Working')?>...';
</script> 

<style>
#<?php echo $randomId?>.registerPopup form {              
    width: <?php echo $this->getData('width')?><?php echo $this->getData('width_unit')==2 ? "%" : "px";?>;
}

#<?php echo $randomId?>.registerPopup form input{
  width: <?php echo $this->getData('width')-20?>px;
  <?php if($this->getData('width_unit')==2):?>
  width:100%;   
  -moz-box-sizing:    border-box;
  -webkit-box-sizing: border-box;
  box-sizing:        border-box;  
  <?php endif;?>
}

#<?php echo $randomId?>.registerPopup button {
    background-color: <?php echo $this->getButtonColor(); ?>;  
    width: <?php echo $this->getData('width')-8?>px;    
    color:<?php echo $this->getButtonTextColor()?>;
    <?php if($this->getData('width_unit')==2):?>
    width:100%;   
    -moz-box-sizing:    border-box;
    -webkit-box-sizing: border-box;
    box-sizing:        border-box;  
    <?php endif;?>    
}  
</style>

<div class="registerPopup tp2" id="<?php echo $randomId?>">   
  <div class="error" style="display:none;"></div>
  <form style="display:none;" action="<?php echo $this->getLoginUrl() ?>" method="post" id="login-form" data-widgetId="<?php echo $this->getWidgetId();?>" class="site-form" onsubmit="return false">      
    <ul>
      <li>
        <input type="text" name="login_email" placeholder="<?php echo __('Enter Your Email')?>" title="<?php echo __('Enter Your Email')?>" />
      </li>
      <li>
        <input type="password"  name="login_password" placeholder="<?php echo __('Password')?>" title="<?php echo __('Select Your Password')?>" />
      </li>  
      <li>
        <button class="async_false" type="submit" title="<?php echo __('Login')?>">
        <?php echo __('Login') ?>
        </button>
      </li>        
    </ul>   
    <p><a href="<?php echo $this->getForgotUrl()?>"><?php echo __('Forgot password?')?></a> | <a href="#" class="register">Register</a></p>
  </form>
  <form action="<?php echo $this->getRegisterUrl() ?>" method="post" id="signup-form" data-widgetId="<?php echo $randomId;?>" class="site-form" onsubmit="return false">
    <ul>
      <li>
        <input type="text" name="firstname" placeholder="<?php echo __('First Name')?>" title="<?php echo __('Enter Your First Name')?>" />
      </li>
      <li>
        <input type="text" name="lastname" placeholder="<?php echo __('Last Name')?>" title="<?php echo __('Enter Your Last Name')?>" />
      </li>
      <li>
        <input type="text" name="email" placeholder="<?php echo __('Your Email')?>" title="<?php echo __('Enter Your Email')?>" />
      </li>
      <li>
        <input type="password" name="password" placeholder="<?php echo __('Select Password')?>" title="<?php echo __('Select Your Password')?>" />
      </li>
      <?php if($this->getData('newsletter_option')==2): ?>
      <li>
        <div id="subscribeNewsletter">
          <input type="checkbox" id="is_subscribed" name="is_subscribed"<?php if($this->getData('checkbox_checked')==1) echo ' checked="checked"'?>>
          <label for="is_subscribed"><?php echo $this->getData('checkbox_text') ? $this->getData('checkbox_text') : __('Subscribe newsletter') ?></label>    
        </div>
      </li>
      <?php endif;?>
      <li>
        <button class="async_false" type="submit" title="<?php echo __('Subscribe')?>">
        <?php echo $this->getData('button_text') ? $this->getData('button_text') : __('Create Account') ?>
        </button>
      </li>
    </ul>    
    <p><a href="#" class="login"><?php echo __('Login')?></a></p>    
  </form>    
</div>  
<!--DONT REMOVE! jQuery use it to check if css is loaded-->
<div class="cssLoadedChecker moctod-dribegam"></div>
<div class="cssLoadedChecker2 moctod-dribegam"></div>
<script src="<?php echo $block->getViewFileUrl('Magebird_Popup::js/register.js') ?>"></script>